name: simple-cprog
base: core18
version: '1.0.0'
summary: Simple C Prog
description: |
  Simple C Prog
grade: stable
confinement: strict
architectures:
  - build-on: amd64

apps:
  curl:
  run-hello-world:
     command: cprog-v1.0.0/a.out 

  
parts:
  cprog:
    source: https://github.com/drunkenlord/c-test/releases/download/v1.0.0/cprog.tar.gz
    plugin: dump
